const express = require('express');
const router = express.Router();
const { verifyAccessToken } = require('../controllers/jwtController');
const bondController = require('../controllers/bondController');
router.post('/toggle/:receiver', verifyAccessToken, bondController.toggleBond);
router.get('/status/:userId', verifyAccessToken, bondController.getStatus);
router.get('/allBondsAndCommunities', verifyAccessToken, bondController.getAllBondsAndCommunities);
router.get('/pending', verifyAccessToken, bondController.getPending);
module.exports = router;
module.exports = router;
